"""create sales data table

Revision ID: 17c1dc000e8f
Revises: 9ce93c469822
Create Date: 2026-09-18 15:10:58.135287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17c1dc000e8f'
down_revision: Union[str, Sequence[str], None] = '9ce93c469822'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_data',
    sa.Column('sales_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('quantity_sold', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('sales_id')
    )
    op.create_index(op.f('ix_sales_data_sales_id'), 'sales_data', ['sales_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_data_sales_id'), table_name='sales_data')
    op.drop_table('sales_data')
    # ### end Alembic commands ###
