"""allow null actual quantity in predictions

Revision ID: b0fbf80504a1
Revises: 85b87a47ef9d
Create Date: 2026-10-07 15:22:17.474618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0fbf80504a1'
down_revision: Union[str, Sequence[str], None] = '85b87a47ef9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modelmetrics', 'lob')
    op.drop_column('modelmetrics', 'train_rows_count')
    op.alter_column('predictions', 'actual_quantity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('predictions', 'actual_quantity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.add_column('modelmetrics', sa.Column('train_rows_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('modelmetrics', sa.Column('lob', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
